blank_issues_enabled: false
contact_links:
  - name: FAQs
    url: https://github.com/infinitepower18/WSA-Sideloader#faq
    about: Have you taken a look at the FAQs?
  - name: Discussion
    url: https://github.com/infinitepower18/WSA-Sideloader/discussions
    about: For other issues, check out the project's discussion section.
