name: Feature request
description: Suggest an idea for this project
title: "[REQUEST]"
body:
  labels: enhancement
    - type: textarea
      id: description
      attributes:
        label: Describe your request
      validations:
        required: true
